---

- name: Create a {{ project_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - ANXS.postgresql
